"""Core data contracts for NeuroForge CFD.

This module is the single source of truth for the data structures that flow
through the whole engine. It depends on **numpy only** (never torch), so that
geometry / data / physics / viz code can import it without pulling in the deep
learning stack.

Tensor & array conventions (read this before touching anything):

* Structured 2D fields are stored as numpy arrays of shape ``(ny, nx)`` with
  ``dtype=float32``, row index = y (j), column index = x (i).
* Grids are built with ``np.meshgrid(x, y, indexing="xy")`` so ``X``/``Y`` have
  shape ``(ny, nx)``.
* Network tensors are channel-first ``(B, C, ny, nx)`` (NCHW).
* Input channels are fixed and ordered by :data:`INPUT_CHANNELS` (7 channels).
* Output channels are fixed and ordered by :data:`OUTPUT_CHANNELS` (4 channels).
* Pressure ``p`` is **kinematic** (p/ρ), matching incompressible RANS / AirfRANS.
* Velocities and pressure are in physical units; physics residuals are always
  computed on **physical (denormalised)** fields.

Do not edit this file as part of a module build — it is a frozen contract.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

import numpy as np

# --------------------------------------------------------------------------- #
# Channel definitions (the network I/O contract)
# --------------------------------------------------------------------------- #

#: Ordered network input channels produced by ``neuroforge.geometry.encode``.
INPUT_CHANNELS: tuple[str, ...] = (
    "sdf",     # signed distance to the body surface (negative inside the solid)
    "mask",    # 1.0 in the fluid, 0.0 in the solid
    "x",       # normalised x coordinate of the cell
    "y",       # normalised y coordinate of the cell
    "u_in",    # freestream / inlet x-velocity, broadcast over the grid
    "v_in",    # freestream / inlet y-velocity, broadcast over the grid
    "log_re",  # log10(Reynolds number), broadcast over the grid
)

#: Ordered network output channels (the predicted solution fields).
OUTPUT_CHANNELS: tuple[str, ...] = (
    "u",    # x-velocity
    "v",    # y-velocity
    "p",    # kinematic pressure (p/rho)
    "nut",  # turbulent (eddy) kinematic viscosity
)

N_IN: int = len(INPUT_CHANNELS)
N_OUT: int = len(OUTPUT_CHANNELS)

DTYPE = np.float32


# --------------------------------------------------------------------------- #
# Fluid / boundary conditions / domain
# --------------------------------------------------------------------------- #


@dataclass
class FluidProperties:
    """Incompressible fluid properties (SI-ish, non-dimensional friendly)."""

    density: float = 1.0
    kinematic_viscosity: float = 1.5e-5  # nu = mu / rho [m^2/s], air at STP-ish

    def reynolds(self, velocity: float, length: float = 1.0) -> float:
        """Reynolds number ``Re = U * L / nu`` for a reference length (chord)."""
        return float(velocity * length / self.kinematic_viscosity)


@dataclass
class BoundaryConditions:
    """Far-field / inlet boundary conditions for an external-aero case."""

    u_inf: float = 1.0          # freestream speed magnitude
    aoa_deg: float = 0.0        # angle of attack in degrees
    reynolds: float = 1.0e6     # chord-based Reynolds number

    def inlet_vector(self) -> tuple[float, float]:
        """Freestream velocity vector ``(u, v)`` from speed and angle of attack."""
        a = np.deg2rad(self.aoa_deg)
        return float(self.u_inf * np.cos(a)), float(self.u_inf * np.sin(a))


@dataclass
class Domain:
    """Rectangular computational domain discretised on a uniform grid."""

    bounds: tuple[float, float, float, float] = (-1.0, 2.0, -1.5, 1.5)  # xmin,xmax,ymin,ymax
    nx: int = 128
    ny: int = 128

    @property
    def dx(self) -> float:
        xmin, xmax, _, _ = self.bounds
        return (xmax - xmin) / (self.nx - 1)

    @property
    def dy(self) -> float:
        _, _, ymin, ymax = self.bounds
        return (ymax - ymin) / (self.ny - 1)

    @property
    def shape(self) -> tuple[int, int]:
        return (self.ny, self.nx)

    def axes(self) -> tuple[np.ndarray, np.ndarray]:
        """1-D coordinate axes ``(x, y)``."""
        xmin, xmax, ymin, ymax = self.bounds
        x = np.linspace(xmin, xmax, self.nx, dtype=DTYPE)
        y = np.linspace(ymin, ymax, self.ny, dtype=DTYPE)
        return x, y

    def grid(self) -> tuple[np.ndarray, np.ndarray]:
        """2-D coordinate grids ``(X, Y)`` of shape ``(ny, nx)``."""
        x, y = self.axes()
        X, Y = np.meshgrid(x, y, indexing="xy")
        return X.astype(DTYPE), Y.astype(DTYPE)


# --------------------------------------------------------------------------- #
# Geometry
# --------------------------------------------------------------------------- #


@dataclass
class Geometry:
    """A closed 2-D body defined by an ordered loop of surface points.

    ``surface_points`` is an ``(N, 2)`` array tracing the body boundary
    counter-clockwise. ``surface_normals``, when present, is an ``(N, 2)`` array
    of outward unit normals at each point. Heavy operations (SDF, masks, normal
    estimation) live in :mod:`neuroforge.geometry.sdf`; this dataclass is pure
    data plus light helpers.
    """

    name: str
    surface_points: np.ndarray              # (N, 2)
    surface_normals: np.ndarray | None = None  # (N, 2) outward unit normals
    meta: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        self.surface_points = np.asarray(self.surface_points, dtype=DTYPE).reshape(-1, 2)
        if self.surface_normals is not None:
            self.surface_normals = np.asarray(self.surface_normals, dtype=DTYPE).reshape(-1, 2)

    @property
    def n_points(self) -> int:
        return int(self.surface_points.shape[0])

    def bounding_box(self) -> tuple[float, float, float, float]:
        p = self.surface_points
        return (float(p[:, 0].min()), float(p[:, 0].max()),
                float(p[:, 1].min()), float(p[:, 1].max()))

    def chord(self) -> float:
        """Streamwise extent of the body (reference length for Re / coefficients)."""
        xmin, xmax, _, _ = self.bounding_box()
        return float(xmax - xmin)


# --------------------------------------------------------------------------- #
# Flow case (the problem statement) and flow field (the solution)
# --------------------------------------------------------------------------- #


@dataclass
class FlowCase:
    """A complete CFD problem: geometry + boundary conditions + fluid + domain."""

    geometry: Geometry
    bc: BoundaryConditions
    fluid: FluidProperties = field(default_factory=FluidProperties)
    domain: Domain = field(default_factory=Domain)
    name: str = "case"

    @classmethod
    def from_airfoil(
        cls,
        airfoil: str = "naca2412",
        aoa: float = 0.0,
        reynolds: float = 3.0e6,
        u_inf: float = 1.0,
        resolution: int = 128,
        n_surface: int = 200,
        domain_bounds: tuple[float, float, float, float] = (-1.0, 2.0, -1.5, 1.5),
    ) -> "FlowCase":
        """Build a case around a NACA airfoil.

        Lazily imports :mod:`neuroforge.geometry.airfoil` to avoid a circular
        dependency. ``reynolds`` and ``u_inf`` jointly fix the kinematic
        viscosity (``nu = u_inf * chord / Re``) so the non-dimensional state is
        consistent.
        """
        from neuroforge.geometry.airfoil import naca_airfoil  # lazy

        geom = naca_airfoil(airfoil, n_points=n_surface)
        chord = max(geom.chord(), 1e-9)
        nu = u_inf * chord / reynolds
        return cls(
            geometry=geom,
            bc=BoundaryConditions(u_inf=u_inf, aoa_deg=aoa, reynolds=reynolds),
            fluid=FluidProperties(density=1.0, kinematic_viscosity=nu),
            domain=Domain(bounds=domain_bounds, nx=resolution, ny=resolution),
            name=f"{airfoil}_aoa{aoa:g}_re{reynolds:.0e}",
        )

    def reference_length(self) -> float:
        return self.geometry.chord()


@dataclass
class FlowField:
    """A flow solution sampled on a structured grid (prediction or ground truth).

    All fields are ``(ny, nx)`` float32. ``mask`` is 1 in the fluid, 0 in the
    solid. ``sdf`` is the signed distance to the surface (negative inside).
    """

    domain: Domain
    u: np.ndarray
    v: np.ndarray
    p: np.ndarray
    nut: np.ndarray | None = None
    mask: np.ndarray | None = None
    sdf: np.ndarray | None = None
    meta: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        for nm in ("u", "v", "p"):
            setattr(self, nm, np.asarray(getattr(self, nm), dtype=DTYPE))
        if self.nut is None:
            self.nut = np.zeros(self.domain.shape, dtype=DTYPE)
        else:
            self.nut = np.asarray(self.nut, dtype=DTYPE)
        if self.mask is None:
            self.mask = np.ones(self.domain.shape, dtype=DTYPE)
        if self.sdf is None:
            self.sdf = np.zeros(self.domain.shape, dtype=DTYPE)

    @property
    def shape(self) -> tuple[int, int]:
        return self.domain.shape

    def speed(self) -> np.ndarray:
        """Velocity magnitude ``sqrt(u^2 + v^2)``."""
        return np.sqrt(self.u ** 2 + self.v ** 2).astype(DTYPE)

    def as_array(self) -> np.ndarray:
        """Stack solution fields into ``(N_OUT, ny, nx)`` in :data:`OUTPUT_CHANNELS` order."""
        return np.stack([self.u, self.v, self.p, self.nut], axis=0).astype(DTYPE)

    @classmethod
    def from_array(
        cls,
        arr: np.ndarray,
        domain: Domain,
        mask: np.ndarray | None = None,
        sdf: np.ndarray | None = None,
        meta: dict[str, Any] | None = None,
    ) -> "FlowField":
        """Inverse of :meth:`as_array`. ``arr`` is ``(N_OUT, ny, nx)``."""
        arr = np.asarray(arr, dtype=DTYPE)
        return cls(domain=domain, u=arr[0], v=arr[1], p=arr[2],
                   nut=arr[3] if arr.shape[0] > 3 else None,
                   mask=mask, sdf=sdf, meta=meta or {})

    def save(self, path: str) -> None:
        """Persist to a ``.npz`` file."""
        np.savez_compressed(
            path, u=self.u, v=self.v, p=self.p, nut=self.nut, mask=self.mask,
            sdf=self.sdf, bounds=np.asarray(self.domain.bounds, dtype=DTYPE),
            nx=self.domain.nx, ny=self.domain.ny,
        )

    @classmethod
    def load(cls, path: str) -> "FlowField":
        d = np.load(path, allow_pickle=False)
        dom = Domain(bounds=tuple(float(b) for b in d["bounds"]),
                     nx=int(d["nx"]), ny=int(d["ny"]))
        return cls(domain=dom, u=d["u"], v=d["v"], p=d["p"], nut=d["nut"],
                   mask=d["mask"], sdf=d["sdf"])


# --------------------------------------------------------------------------- #
# Diagnostics (physics checker output) and solve result
# --------------------------------------------------------------------------- #


@dataclass
class Diagnostics:
    """Self-assessment of a predicted field: residuals, uncertainty, trust.

    All maps are ``(ny, nx)`` float32. ``trust`` is in ``[0, 1]`` (1 = reliable).
    ``trust_class`` is an integer map: 2 = green (reliable), 1 = yellow
    (acceptable), 0 = red (needs correction/refinement).
    """

    continuity: np.ndarray
    momentum_x: np.ndarray
    momentum_y: np.ndarray
    bc_violation: np.ndarray
    uncertainty: np.ndarray
    trust: np.ndarray
    trust_class: np.ndarray
    summary: dict[str, float] = field(default_factory=dict)

    def residual_norm(self) -> float:
        """Scalar L2 residual magnitude used as the convergence signal."""
        r = np.sqrt(self.continuity ** 2 + self.momentum_x ** 2 + self.momentum_y ** 2)
        return float(np.sqrt(np.mean(r ** 2)))


@dataclass
class SolveResult:
    """The full output of :meth:`NeuroForgeEngine.solve`."""

    case: FlowCase
    field: FlowField
    diagnostics: Diagnostics
    metrics: dict[str, float] = field(default_factory=dict)
    history: list[dict[str, float]] = field(default_factory=list)
    meta: dict[str, Any] = field(default_factory=dict)

    def save_report(self, path: str, **kwargs: Any) -> str:
        """Render an HTML/PNG report. Lazily imports :mod:`neuroforge.viz.report`."""
        from neuroforge.viz.report import build_report  # lazy
        return build_report(self, path, **kwargs)

    def summary(self) -> dict[str, float]:
        out = dict(self.metrics)
        out["residual_norm"] = self.diagnostics.residual_norm()
        out["n_iters"] = float(len(self.history))
        return out
