"""Self-contained HTML report generation for a :class:`SolveResult`.

:func:`build_report` renders the multi-panel :func:`overview_figure`, embeds it
as a base64 PNG inside a single standalone HTML file (no external assets), also
writes a sibling ``<path>.png``, and includes a small metrics table from
``result.summary()``. This is what :meth:`SolveResult.save_report` calls.
"""

from __future__ import annotations

import base64
import html
import io
import os
from datetime import datetime

import matplotlib

matplotlib.use("Agg")  # headless, before pyplot

import matplotlib.pyplot as plt  # noqa: E402

from neuroforge.core.types import SolveResult  # noqa: E402

from .plots import overview_figure  # noqa: E402

__all__ = ["build_report"]


_CSS = """
:root { color-scheme: light dark; }
body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
       margin: 0; padding: 2rem; background: #f7f7f8; color: #1a1a1a; }
.wrap { max-width: 1100px; margin: 0 auto; }
h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
.sub { color: #666; margin: 0 0 1.5rem; font-size: .9rem; }
.card { background: #fff; border: 1px solid #e3e3e6; border-radius: 10px;
        padding: 1.25rem; margin-bottom: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,.04); }
img { max-width: 100%; height: auto; display: block; border-radius: 6px; }
table { border-collapse: collapse; width: 100%; font-size: .9rem; }
th, td { text-align: left; padding: .45rem .75rem; border-bottom: 1px solid #ececef; }
th { background: #fafafa; font-weight: 600; }
td.val { font-variant-numeric: tabular-nums; text-align: right; }
.footer { color: #999; font-size: .8rem; text-align: center; margin-top: 1rem; }
code { background: #f0f0f2; padding: .1rem .35rem; border-radius: 4px; }
"""


def _fig_to_png_bytes(fig: plt.Figure, dpi: int = 110) -> bytes:
    """Render a figure to PNG bytes."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight")
    buf.seek(0)
    return buf.read()


def _format_value(v: float) -> str:
    """Pretty-print a metric value."""
    try:
        fv = float(v)
    except (TypeError, ValueError):
        return html.escape(str(v))
    if fv == int(fv) and abs(fv) < 1e6:
        return f"{int(fv)}"
    return f"{fv:.5g}"


def _metrics_table(summary: dict) -> str:
    """Build an HTML table from a metrics summary dict."""
    rows = []
    for k in sorted(summary):
        rows.append(
            f"<tr><th>{html.escape(str(k))}</th>"
            f"<td class='val'>{_format_value(summary[k])}</td></tr>"
        )
    return (
        "<table><thead><tr><th>metric</th><th class='val'>value</th></tr></thead>"
        "<tbody>" + "".join(rows) + "</tbody></table>"
    )


def build_report(result: SolveResult, path: str, title: str | None = None) -> str:
    """Write a standalone HTML report (+ sibling PNG) for a solve result.

    Parameters
    ----------
    result : SolveResult
        The solve output to summarise.
    path : str
        Destination HTML path. Parent directories are created if needed. A
        sibling PNG is written at ``<path>.png`` (e.g. ``report.html.png``).
    title : str, optional
        Report title; defaults to the case name.

    Returns
    -------
    str
        The HTML path written.
    """
    path = os.fspath(path)
    parent = os.path.dirname(os.path.abspath(path))
    os.makedirs(parent, exist_ok=True)

    title = title or f"NeuroForge CFD — {result.case.name}"

    fig = overview_figure(result)
    try:
        png_bytes = _fig_to_png_bytes(fig)
    finally:
        plt.close(fig)

    # Sibling PNG next to the HTML.
    png_path = path + ".png"
    with open(png_path, "wb") as fh:
        fh.write(png_bytes)

    b64 = base64.b64encode(png_bytes).decode("ascii")
    summary = result.summary()
    table_html = _metrics_table(summary)

    case = result.case
    bc = case.bc
    case_desc = (
        f"airfoil <code>{html.escape(case.geometry.name)}</code> &middot; "
        f"AoA {bc.aoa_deg:g}&deg; &middot; Re {bc.reynolds:.3g} &middot; "
        f"U&#8734; {bc.u_inf:g} &middot; grid {case.domain.nx}&times;{case.domain.ny}"
    )
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>{_CSS}</style>
</head>
<body>
<div class="wrap">
  <h1>{html.escape(title)}</h1>
  <p class="sub">{case_desc}</p>

  <div class="card">
    <img src="data:image/png;base64,{b64}" alt="solve overview">
  </div>

  <div class="card">
    <h2 style="margin-top:0;font-size:1.1rem;">Metrics</h2>
    {table_html}
  </div>

  <p class="footer">Generated by NeuroForge CFD on {now}</p>
</div>
</body>
</html>
"""

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(doc)

    return path
