"""Generate results/MANIFEST.json — an artifact-evaluation manifest covering ALL
headline result directories (not just full_research).

Unlike results/full_research/MANIFEST.json (which the full-research run writes for
its own two output dirs), this top-level manifest is a *post-hoc* inventory of
every committed headline result file the paper cites, with:

  * a real SHA-256 hash computed from the committed file on disk (never fabricated),
  * the file size and last-commit SHA touching it (best-effort, via git),
  * the producing script (mapped explicitly, verified by grep at authoring time),
  * the runtime tier (CPU-verify vs GPU-regenerate).

It also records the environment that PRODUCED the headline numbers (from the
existing full_research/MANIFEST.json, the calibrated run env) plus the CURRENT
environment generating this manifest, and the current git HEAD.

This is a reproducibility aid, NOT a result — it is safe to regenerate any time:

    .venv/Scripts/python.exe scripts/make_manifest.py            # -> results/MANIFEST.json
    .venv/Scripts/python.exe scripts/make_manifest.py --check    # verify hashes match, exit 1 on drift

CPU-only, no torch/numpy needed (pure stdlib), seconds to run.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# The headline result files the paper cites, mapped to their producing script
# and runtime tier. Mapping was verified by grepping each filename across
# scripts/ + benchmarks/ for the write site (open(...,'w')/json.dump/savefig).
# tier: "gpu" = regenerated by a multi-day GPU run; "cpu" = re-derivable on a
# laptop FROM a (gitignored) checkpoint; "cpu-verify" = pure plotting/inventory.
# ---------------------------------------------------------------------------
HEADLINE: list[dict] = [
    # --- SOTA Transolver headline (tab:v2, abstract) ---
    {"path": "results/v2/v2_results.json",
     "script": "scripts/run_v2.py", "tier": "gpu",
     "claims": "Transolver backbone -9/-21/-25% MSE; rho_Cl 0.999; trust rho 0.625; MC-dropout coverage 0.902"},
    # --- third backbone, trust signal (tab in sec:v2) ---
    {"path": "results/mgn/mgn_results.json",
     "script": "scripts/run_mgn.py", "tier": "gpu",
     "claims": "MeshGraphNet bare trust rho 0.851"},
    # --- deep-ensemble adaptive UQ (tab:uq) ---
    {"path": "results/uq_ensemble/uq_results.json",
     "script": "scripts/run_ensemble_uq.py", "tier": "gpu",
     "claims": "deep-ensemble conformal coverage 0.915, ECE 0.074, q 2.35; ensemble-mean accuracy"},
    {"path": "results/uq_ensemble/w2_conformal_corrected.json",
     "script": "scripts/run_w2_conformal_corrected.py", "tier": "gpu",
     "claims": "W2 — conformal coverage on the deployed DEQ-corrected Transolver field"},
    # --- W1 residual-input ablation (abstract, sec:v2, limitations) ---
    {"path": "results/control/w1_capture.json",
     "script": "scripts/run_w1_capture.py", "tier": "gpu",
     "claims": "5-seed extension: backbone trust rho 0.611 +/- 0.054 (positive 5/5); corrector -8/-21/-25%; "
               "W1 null corrector matches/exceeds residual-fed on 5/5 seeds (gain not from residual input)"},
    # --- force coefficients vs official AirfRANS labels (sec:v2, SOTA positioning) ---
    {"path": "results/control/force_vs_official.json",
     "script": "scripts/recompute_force_vs_official.py", "tier": "gpu",
     "claims": "vs official labels rho_D 0.839, rho_L 0.879; self-consistency 0.995/0.999 reproduced"},
    # --- drag observability: raster round trip through AirfRANS's own integrator ---
    {"path": "results/control/drag_observability_roundtrip.json",
     "script": "scripts/drag_observability_roundtrip.py", "tier": "cpu",
     "claims": "raster round trip scored by AirfRANS's OWN integrator: rho_D 0.700 / "
               "0.710 / 0.762 at 128/256/512 vs rho_L 0.9967 / 0.9986 / 0.9995; "
               "viscous drag recovered to 0.55%/1.05%/1.91% of its value; verdict "
               "R-WORSE (raster owns the loss, 0.839 is not a ceiling); all 4 gates 0.0"},
    # --- covariate control: how much of a drag rho is just knowing the case ---
    {"path": "results/control/drag_covariate_control.json",
     "script": "scripts/drag_covariate_control.py", "tier": "cpu",
     "claims": "(U,alpha,alpha^2) regression on the simulation NAME ranks official cd at "
               "0.874, beating every ground-truth integrator arm (0.611-0.839) and every "
               "prediction (0.828-0.845); partial rho_D drops to 0.53-0.65, partial rho_L "
               "holds at 0.85-0.9999"},
    # --- per-cell vs per-case trust scope ---
    {"path": "results/control/percell_residual_error.json",
     "script": "scripts/control_percell_residual_error.py", "tier": "cpu",
     "claims": "per-cell trust 0.22 Spearman / 0.60 Pearson (case-level vs per-cell scope)"},
    # --- BC-inclusive residual robustness (residual_floor_theorem) ---
    {"path": "results/control/bc_inclusive_sweep.json",
     "script": "scripts/control_bc_inclusive_residual.py", "tier": "cpu",
     "claims": "residual-as-objective negative survives the BC (no-slip) term"},
    # --- cross-geometry cylinder OOD (sec:ood, fig:cylinder) ---
    {"path": "results/figures/cylinder_control_airfoil_ratio.json",
     "script": "scripts/control_cylinder_nearwall_artifact.py", "tier": "cpu",
     "claims": "cylinder far-field residual ~7x in-dist; near-wall ring is a generic feature (control)"},
    # --- certificates H4 / H5 / residual floor ---
    {"path": "results/certificates/h4_coverage.json",
     "script": "scripts/run_certificates.py", "tier": "cpu",
     "claims": "H4 in-distribution split-conformal coverage 0.911/0.928/0.942"},
    {"path": "results/certificates/h5_contraction.json",
     "script": "scripts/run_certificates.py", "tier": "cpu",
     "claims": "H5 DEQ contraction median 0.78 < kappa 0.9"},
    {"path": "results/certificates/residual_floor_realdata.json",
     "script": "scripts/probe_residual_floor.py", "tier": "cpu",
     "claims": "residual floor: ||r*|| mean 0.192; uniform field gives 0 (theorem H2)"},
    {"path": "results/certificates/transolver_inversion.json",
     "script": "scripts/probe_transolver_inversion.py", "tier": "gpu",
     "claims": "the 160/200 prediction-below-floor inversion is backbone-specific and does "
               "NOT survive on the deployed Transolver: 8/5/5 of 200 (backbone alone) and "
               "12/9/14 of 200 (Transolver+DEQ) across seeds 0/1/2, median gap +0.013..+0.015 "
               "ABOVE the floor vs -0.024 BELOW for the dropout-FNO. Identity gates both pass "
               "(truth floor reproduces the committed per_case exactly, max_abs_diff 0; the "
               "dropout-FNO row reproduces mean/std/160 to all digits). Banded gradient energy: "
               "dropout-FNO 1.75x the truth's, Transolver 1.00x, so 'over-smoothed' is wrong too"},
    {"path": "results/certificates/floor_resolution_decomposition.json",
     "script": "scripts/floor_resolution_decomposition.py", "tier": "cpu",
     "claims": "the residual floor does NOT decay under refinement: p=-0.64+-0.29 on a "
               "fixed physical region, 0/16 cases decay, 15/16 rise, x2.34 ratio-of-means over "
               "128^2-512^2 (x2.56 mean-of-per-case-ratios, the JSON fine_over_coarse field); "
               "MMS truncation gate p=2.02; 128^2 rung reproduces the published floor to 3e-8"},
    {"path": "results/certificates/floor_cloud_decimation.json",
     "script": "scripts/floor_cloud_decimation.py", "tier": "cpu",
     "claims": "the discriminating test for the floor's MECHANISM. Holding h fixed and "
               "decimating the source point cloud (nested subsets D=1/2/4/8, geometry built "
               "from the FULL cloud so sdf/mask/bands are identical at every D) raises the "
               "floor in 16/16 cases, on all three bands, at both rungs: exponent "
               "q = d log(floor)/d log(s) = +0.55/+0.45 (band 0.1, n=128/256), rise x1.8 at "
               "D=8. Operator provenance predicted q=0 and is REFUTED (sign test p=3e-5); "
               "the pre-registered representation model predicted q=1-p_h=1.64 and is ALSO "
               "refuted (1/16 cases reach q>=1). Registered branch: REPRESENTATION-PARTIAL. "
               "Gates: D=1 reproduces floor_resolution_decomposition.json per-case to "
               "worst_rel 0.0 over 128 comparisons; hull fallback 0 at every D"},
    {"path": "results/certificates/floor_collapse_analysis.json",
     "script": "scripts/floor_collapse_analysis.py", "tier": "cpu",
     "claims": "POST-HOC, not pre-registered. Pools the decimation grid with the committed "
               "5-rung ladder (11 points per case per band). The registered model q-1=r holds "
               "in 1/16 cases; the one-group s/h form q=r holds in 7/16 and wins on adjusted "
               "R^2 in 13-14/16. Pooled over 3 bands x 5 rungs x 4 decimations (33 cells) "
               "floor ~ (h/s)^-0.48, R^2=0.71, median scatter 12%%. The s-exponent is 66-92%% "
               "of the h-exponent, so most of the refinement-driven growth is reproduced by "
               "thinning the cloud at fixed grid. Per-case the collapse does NOT hold"},
    {"path": "results/certificates/probe_conformal_after_deq.json",
     "script": "scripts/probe_conformal_after_deq.py", "tier": "cpu",
     "claims": "conformal survives DEQ (20/20 independent split)"},
    {"path": "results/certificates/verify_conformal_corrected_field.json",
     "script": "scripts/verify_conformal_corrected_field.py", "tier": "cpu",
     "claims": "certificate on the deployed corrected field (15/15 split)"},
    # --- sensitivity sweeps (tab:iters, toggles, OOD coverage) ---
    {"path": "results/sensitivity/iters.csv",
     "script": "scripts/run_sensitivity.py", "tier": "cpu",
     "claims": "tab:iters — residual rises monotonically (0.11->0.62) while surface mse_p "
               "falls monotonically (541204->300664, rank corr -0.94). mse_u is NOT "
               "monotone: it bottoms at iter 3 (2.287) and rises 12.6% to 2.575 by iter 15, "
               "so it moves WITH the residual on 3 of the 5 intervals (rank corr -0.03). "
               "Row 0 is backbone-only, so 0->1 is a corrector-on/off contrast, not an "
               "iteration step; for n_iters>=1 alone the residual rises 84.7% and mse_u "
               "rises 4.7%. Not a test of residual minimisation -- that is "
               "results/residual_descent/"},
    {"path": "results/sensitivity/iters.json",
     "script": "scripts/run_sensitivity.py", "tier": "cpu",
     "claims": "iteration-sensitivity sweep (json form of tab:iters)"},
    {"path": "results/sensitivity/iters_seeded.json",
     "script": "scripts/iters_sweep_seeded.py", "tier": "gpu",
     "claims": "seeded tab:iters on 5 Transolver+DEQ seeds: DIRECTION-ONLY. Residual up in "
               "5/5 seeds but only +1.5% (1.3x seed sd) and higher per case in 30/72 = 42%; "
               "monotone in 0/5. Decoupling, not divergence."},
    {"path": "results/sensitivity/iters_seeded.csv",
     "script": "scripts/iters_sweep_seeded.py", "tier": "gpu",
     "claims": "mean+-sd over 5 seeds per iteration cap (csv form)"},
    # --- residual descent at n=200 (sec:descent, deployed-backbone arms) ---
    {"path": "results/residual_descent/verification.json",
     "script": "scripts/residual_descent_test.py", "tier": "cpu",
     "claims": "the differentiable objective IS the monitored scalar: sqrt(2J) matches "
               "Diagnostics.residual_norm to 9.9e-8 relative; uniform freestream gives "
               "exactly 0 (theorem leg i); ||r*|| mean 0.178 (H2)"},
    {"path": "results/residual_descent/descent_truth_bc_uvp_armijo.json",
     "script": "scripts/residual_descent_test.py", "tier": "cpu",
     "claims": "theorem leg (ii) measured: Armijo gradient descent from the ground truth "
               "with Dirichlet data pinned at truth cuts J to 39.8% while field error "
               "rises on 200/200 cases and never returns to its start in 500 steps; "
               "end rel-L2 0.0069 = 1.57x the deployed Transolver's entire error"},
    {"path": "results/residual_descent/descent_transolver_seed0_bc_uvp_armijo.json",
     "script": "scripts/residual_descent_test.py", "tier": "cpu",
     "claims": "deployed backbone, seed 0: residual -34% while rel-L2 rises on 96.5% of "
               "200 cases (median +76.5%, Wilcoxon p=2.3e-32)"},
    {"path": "results/residual_descent/eta_sensitivity.json",
     "script": "scripts/residual_descent_test.py", "tier": "cpu",
     "claims": "eta swept over 12 decades, 6 (arm,mode) blocks: on the deployed backbone "
               "error worsens monotonically with the ACHIEVED J reduction (no good eta "
               "exists); on the far-from-floor dropout-FNO the same sweep runs the other "
               "way (-14.8% at J/J0=0.34), which is why the claim is a regime claim"},
    {"path": "results/residual_descent/regime_boundary.json",
     "script": "scripts/residual_descent_test.py", "tier": "cpu",
     "claims": "regime boundary in the theorem's own variable rho=||R_h(u_hat)||/||r*||: "
               "fraction helped rises monotonically with rho; deployed Transolver sits at "
               "median rho=1.13-1.14 with 88% of cases in the bin where descent helps 0-1%"},
    {"path": "results/residual_descent/summary.json",
     "script": "scripts/residual_descent_test.py", "tier": "cpu",
     "claims": "index of all 16 descent runs (3 step rules, 5 start fields, 2 constraint "
               "modes) with their aggregates and measured wall_s"},
    {"path": "results/sensitivity/toggles.json",
     "script": "scripts/run_sensitivity.py", "tier": "cpu",
     "claims": "trust-gate / acceptance-test toggles are structural no-ops on DEQ"},
    {"path": "results/sensitivity/ood_coverage.json",
     "script": "scripts/run_sensitivity.py", "tier": "cpu",
     "claims": "OOD conformal coverage stays in-band (empirical, sec:conformal)"},
    # --- weak-grid-backbone ablations (tab:indist, tab:ood) ---
    {"path": "results/full_research/in_dist/ablation.md",
     "script": "scripts/run_full_research.py", "tier": "gpu",
     "claims": "tab:indist — weak backbone trust 0.40->0.83; corrector trades accuracy"},
    {"path": "results/full_research/in_dist/ablation.csv",
     "script": "scripts/run_full_research.py", "tier": "gpu",
     "claims": "tab:indist (csv)"},
    {"path": "results/full_research/ood/ablation_ood.md",
     "script": "scripts/run_full_research.py", "tier": "gpu",
     "claims": "tab:ood — aoa trust collapse 0.31->0.75 rescued by corrector"},
    {"path": "results/full_research/ood/ablation_ood.csv",
     "script": "scripts/run_full_research.py", "tier": "gpu",
     "claims": "tab:ood (csv)"},
    # --- matched-budget baseline (tab:transolver) ---
    {"path": "results/baselines/table2.md",
     "script": "scripts/run_baselines.py", "tier": "gpu",
     "claims": "tab:transolver — grid backbone trails Transolver 4-60x"},
    {"path": "results/baselines/table2.csv",
     "script": "scripts/run_baselines.py", "tier": "gpu",
     "claims": "tab:transolver (csv)"},
    # --- second dataset (DeepCFD, laminar bluff bodies) ---
    {"path": "results/deepcfd/deepcfd_results.json",
     "script": "scripts/run_deepcfd.py", "tier": "gpu",
     "claims": "DeepCFD OOD trust rho 0.770 +/- 0.119 (3 seeds, interior residual)"},
    {"path": "results/deepcfd/deepcfd_trust_percase.json",
     "script": "scripts/make_fig_deepcfd_trust.py", "tier": "cpu",
     "claims": "per-case (residual, rel-L2) dump behind fig:deepcfd + bootstrap CIs"},
    # --- selective prediction / risk-coverage (fig:risk_coverage) ---
    {"path": "results/selective/selective_prediction.json",
     "script": "scripts/run_selective_prediction.py", "tier": "cpu",
     "claims": "AUROC 0.87-0.91 residual, 0.905 fused; ~91% of oracle error reduction at 10% rejection"},
    {"path": "results/selective/selective_percase.json",
     "script": "scripts/run_selective_prediction.py", "tier": "cpu",
     "claims": "per-case scores/errors for all arms (bootstrap-CI input)"},
    {"path": "results/figures/fig_risk_coverage.pdf",
     "script": "scripts/run_selective_prediction.py", "tier": "cpu",
     "claims": "fig:risk_coverage (risk-coverage curves + AUROC bars)"},
    # --- multi-split conformal robustness (sec:conformal) ---
    {"path": "results/uq_ensemble/multisplit_conformal.json",
     "script": "scripts/run_multisplit_conformal.py", "tier": "cpu",
     "claims": "20-split conformal: coverage 0.895-0.902 all arms; corrected-p q 2.26->2.02-2.07"},
    # --- bootstrap CIs on the trust-signal Spearman headlines ---
    {"path": "results/control/bootstrap_spearman_ci.json",
     "script": "scripts/bootstrap_spearman_ci.py", "tier": "cpu",
     "claims": "case-level bootstrap 95% CIs; all arms exclude zero (ensemble 0.610 [0.51,0.70])"},
    # --- force-integrator repair (sec:v2 force paragraphs) ---
    {"path": "results/control/integrator_design.json",
     "script": "scripts/design_force_integrator.py", "tier": "cpu",
     "claims": "GT-field integrator variants: CV rho_L 1.00 / cd med 0.23; wall cl med 0.046"},
    {"path": "results/control/force_vs_official_multischeme.json",
     "script": "scripts/recompute_force_multischeme.py", "tier": "gpu",
     "claims": "pred fields: CV lift rho_L 0.998 +/- 0.001, cl med err 3.6-3.9%/seed; drag model-limited"},
    # --- spatial trust localization (per-cell vs patch scope) ---
    {"path": "results/control/percell_localization.json",
     "script": "scripts/percell_trust_localization.py", "tier": "cpu",
     "claims": "cell-level rho 0.166 -> 16x16-patch 0.323 (93% of cases improve); patch AUROC 0.68-0.72"},
    # --- acceptance-gate measurement (sec:iters, the residual-as-GATE verdict) ---
    {"path": "results/control/acceptance_gate.json",
     "script": "scripts/measure_acceptance_gate.py", "tier": "gpu",
     "claims": "monotone-residual gate admits a step on 99.8%% of deployed cases (the full "
               "correction on 50.7%%); the admitted step lowers true rel-L2 error on 89.3%% of "
               "them by a median 5.8%% -- the guarantee is real AND useful, not vacuous"},
    # --- audit wall-clock cost (selective-prediction paragraph) ---
    {"path": "results/control/audit_cost.json",
     "script": "scripts/measure_audit_cost.py", "tier": "cpu",
     "claims": "full audit median 1.7 ms/case (1 CPU thread) vs ~25-min 16-core RANS solve (~1e-6)"},
    # --- is the nu_t channel actually learned? (Limitations, sec:method) ---
    {"path": "results/control/nut_learned.json",
     "script": "scripts/check_nut_learned.py", "tier": "cpu",
     "claims": "nu_t over fluid cells mean 8.19e-5 vs laminar nu 1.56e-5 (5.2x, 84%% of nu_eff); channel is learned, backbone-dependently: R2 0.996 grid backbone, 0.67-0.70 MeshGraphNet against nu_t's own fluid-masked variance"},
    # --- does any no-slip weight rescue the residual? (sec:residual_floor) ---
    {"path": "results/control/bc_weight_sweep.json",
     "script": "scripts/bc_weight_sweep.py", "tier": "cpu",
     "claims": "post-hoc sweep of the no-slip weight lambda on already-logged components: the uniform field stays a spurious minimum and the residual still rises as error falls, for every lambda >= 0 (closed form, no crossover weight)"},
    # --- full-pipeline wall-clock cost (sec:cost, JCP complexity requirement) ---
    {"path": "results/control/inference_cost.json",
     "script": "scripts/measure_inference_cost.py", "tier": "gpu",
     "claims": "deployed solve 3822 ms/case (backbone 2080 + correction 1747) on one RTX 4070 Ti; audit 1.13 ms = 0.03%% of it; 5-member ensemble 4.86x a single backbone "
               "(linear in M, measured not assumed); audit O(N) in cells, slope 0.64 over a 16x range; ~286x faster end-to-end than the ~25-min 16-core RANS solve"},
    # --- ensemble-size study (limitations: choice of M measured) ---
    {"path": "results/uq_ensemble/mstudy.json",
     "script": "scripts/run_ensemble_mstudy.py", "tier": "gpu",
     "claims": "M=2..5 all 26 subsets: fused AUROC 0.905-0.912 + coverage on-target at every M; "
               "band adaptivity needs M (q_p 2.35->9.98, ECE 0.074->0.199 as M 5->2)"},
    # --- graphical abstract (JCP submission artefact) ---
    {"path": "results/figures/graphical_abstract.pdf",
     "script": "scripts/make_graphical_abstract.py", "tier": "cpu",
     "claims": "predict -> audit -> calibrate -> decide strip; median-error showcase case, committed numbers only"},
    # --- decisive controls from the adversarial reviews (docs/paper/review/decisive_controls.md) ---
    {"path": "results/review/control1_physics_vs_physicsfree.json",
     "script": "scripts/decisive_controls.py --control 1", "tier": "cpu-verify",
     "claims": "paired case-level bootstrap (1e4 draws, fixed top-decile threshold) of the "
               "residual/sigma_vel/fused differences: sigma-residual dAUROC +0.023 CI [-0.035,+0.083] "
               "(includes zero, underpowered at n=200); fused-residual +0.035 CI [+0.005,+0.069] (real); "
               "fused-sigma significant on Spearman only"},
    {"path": "results/review/control2_difficulty_confound.json",
     "script": "scripts/decisive_controls.py --control 2", "tier": "cpu-verify",
     "claims": "partial Spearman given ||r(truth)||: 0.561 vs raw 0.610 on the Transolver arm "
               "(92%% survives, drop CI includes zero); the deployable residual significantly "
               "outranks the oracle difficulty variable itself (drho +0.094 CI [+0.055,+0.142])"},
    {"path": "results/review/control3_fixed_step.json",
     "script": "scripts/control_fixed_step.py", "tier": "cpu",
     "claims": "ungated fixed-step control on the acceptance gate: fixed 0.5 improves 95.8%% of "
               "deployed cases (median -6.2%%) vs the gate's 89.2%% (-5.8%%), so the accuracy is "
               "damping not the residual test; the gate's exclusive contribution is the certificate "
               "(ungated 0.5 breaks monotonicity on 1.0%% deployed / 8.8%% ensemble-path cases)"},
    {"path": "results/review/control4_riskcoverage_drag.json",
     "script": "scripts/decisive_controls.py --control 4", "tier": "cpu-verify",
     "claims": "risk-coverage with |dCd| as the error target: residual AUROC 0.952 (vs 0.871 on "
               "field error), oracle recovery 0.805; physics beats physics-free here "
               "(dAUROC +0.055..+0.088, CIs exclude zero in 5/6 arms) and fusion stops helping"},
    {"path": "results/review/control5_mgn_density_disclosure.json",
     "script": "scripts/decisive_controls.py --control 5", "tier": "cpu-verify",
     "claims": "disclosure audit: mgn_density_control.json has 0 mentions in docs/paper outside "
               "review notes; it shows a 11x train/eval density mismatch inflating velocity MSE "
               "2.44x on 4 cases, but measures MSE not rho and does NOT establish that rho=0.851 "
               "is a density artifact"},
    {"path": "results/review/control6_iters_channels.json",
     "script": "scripts/decisive_controls.py --control 6", "tier": "cpu-verify",
     "claims": "tab:iters channel availability + monotonicity: mse_v/mse_p/mse_nut absent from the "
               "committed sweep; mse_u bottoms at iter 3 (2.287) and rises 12.6%% to 2.575 by iter 15 "
               "while residual_norm rises 14.4%%, so over iters 3-15 residual and error move the SAME way"},
    {"path": "results/review/control6_iters_full_channels.json",
     "script": "scripts/control_iters_channels.py", "tier": "cpu",
     "claims": "iters sweep re-run on the retained checkpoint with every channel kept (same "
               "permuted 80-case subset as run_sensitivity, reproduction-gated against iters.json): "
               "recovers the mse_v / mse_p / mse_nut columns tab:iters omits"},

    # --- the functional audit gate (docs/paper/review/functional_audit_gate.md) ---
    {"path": "results/review/functional_audit_gate_validation.json",
     "script": "scripts/functional_audit_gate.py --validate", "tier": "cpu-verify",
     "claims": "plumbing validation of the drag-direction functional residual BEFORE the "
               "hypothesis tests: box telescoping closes to 5.2e-13 on a body-free box; the "
               "surface-term identity phi_outer = I_T0 + i_solid + i_ring closes to 5.9e-15, so "
               "the immersed body's term is accounted rather than dropped; the sign agrees with "
               "design_force_integrator.py's control-volume convention on 6/6 cases"},
    {"path": "results/review/functional_audit_gate.json",
     "script": "scripts/functional_audit_gate.py --run", "tier": "cpu",
     "claims": "per-case drag-direction functional residual I(w;V) = e_D.int_V R dV on 200 "
               "AirfRANS full/test cases x 8 fields (truth, raw+corrected for 3 v2_transolver "
               "seeds, ensemble mean) x 5 nested control volumes x advective/conservative forms "
               "x 3 wall-ring treatments, plus the unsigned contrasts and the telescoped "
               "far-field flux; zero forward passes, committed caches only"},
    {"path": "results/review/functional_audit_gate_analysis.json",
     "script": "scripts/functional_audit_gate.py --analyse", "tier": "cpu",
     "claims": "the pre-registered gate (rule committed in 282b00e BEFORE the run) applied "
               "mechanically: (a) FAILS -- functional inversion 27-36%% against a 10%% bar and a "
               "2.5-6.5%% matched norm-level baseline; (b) FAILS -- AUROC 0.61-0.70 against the "
               "residual norm's 0.94-0.96; (c) not built; branch = Design A. Also records that "
               "the truth's own functional residual is 9.6-10.3x the median |dCd| it would "
               "certify, so the floor does not cancel under integration"},
    {"path": "results/review/functional_audit_gate_bootstrap.json",
     "script": "scripts/functional_audit_gate.py (targeted paired bootstrap)", "tier": "cpu-verify",
     "claims": "paired case-level bootstrap, 10^4 draws, top-decile threshold held fixed: the "
               "signed functional is significantly WORSE than the residual norm (dAUROC -0.25 to "
               "-0.47, every CI excludes zero), while the UNSIGNED integral of the same cells is "
               "indistinguishable on AUROC (CIs include zero) and significantly better on "
               "Spearman (+0.059..+0.132, 3/3 CIs exclude zero) -- cancellation identified as the "
               "mechanism by measurement rather than by argument"},
    {"path": "results/review/floor_subtraction_gate.json",
     "script": "scripts/floor_subtraction_gate.py", "tier": "cpu",
     "claims": "kills the manuscript's causal clause that the conformal bound is wide BECAUSE "
               "86%% of a typical score is floor. Oracle counterfactual: sigma' = "
               "||R(u_hat) - R(u*)|| (a FIELD difference; a difference of norms is not a valid "
               "decomposition and ||R(u_hat)|| < ||r*|| on 2.5-4.0%% of cases). Removing the "
               "floor exactly makes the bound WIDER, 7.4x -> 11.3x, on 3/3 seeds, against a "
               "pre-registered FLOOR-CAUSAL threshold of <=2x. Mechanism: the width tracks "
               "Q_0.9/median of the nonconformity ratio (15.1 uninformative / 6.3 deployed / "
               "10.5 floor-subtracted) and floor subtraction IMPROVES the ranking "
               "(Spearman 0.62->0.68) while DEGRADING the scale. Since the oracle r* dominates "
               "any learned r_hat*, this also closes the constructive half of Target C. The "
               "deployed monitor buys 2.34x over no monitor at all"},
    {"path": "results/review/functional_audit_gate_followup.json",
     "script": "scripts/functional_audit_gate.py --followup", "tier": "cpu-verify",
     "claims": "two controls the gate's own results forced. F1: the residual NORM passes the "
               "gate's own inversion bar on the deployed arm, so the 'cannot certify' leg is "
               "restated as a WIDTH -- split conformal at the EXACT ceil((1-a)(n+1)) order "
               "statistic attains 0.901-0.903 coverage at a 0.90 target with a bound 6.5-7.9x "
               "the median |dCd| and 1.7x the median field rel-L2. (Before 2026-09-07 this used "
               "a plain np.quantile, which lands at position 90.1/100 and delivered exactly the "
               "predicted 0.891-0.895; the fix raised the width by 15-17%%.) "
               "median ||R(truth)||/median ||R(pred)|| = 0.864, i.e. 86%% of a typical score is "
               "floor present at zero error -- but see floor_subtraction_gate.json: that share "
               "is NOT what makes the bound wide. F2: the far-field flux beats the surface integrator "
               "on GROUND-TRUTH fields (rho 0.985 vs 0.839) and LOSES on PREDICTED fields "
               "(0.37-0.49 vs 0.83-0.85), which withdraws an integrator recommendation an earlier "
               "draft of the report made"},
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def git(*args: str) -> str | None:
    try:
        out = subprocess.run(["git", "-C", str(REPO), *args],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except Exception:
        return None


def is_tracked(rel: str) -> bool:
    return git("ls-files", "--error-unmatch", rel) is not None


def build() -> dict:
    head = git("rev-parse", "HEAD")
    head_short = git("rev-parse", "--short", "HEAD")

    # Environment that PRODUCED the headline numbers (calibrated run env).
    produced_env = None
    fr = REPO / "results" / "full_research" / "MANIFEST.json"
    if fr.exists():
        m = json.loads(fr.read_text())
        produced_env = {k: m.get(k) for k in
                        ("git_commit", "platform", "python", "torch",
                         "cuda_available", "cuda_toolkit", "gpu")}

    files = []
    missing = []
    for entry in HEADLINE:
        rel = entry["path"]
        p = REPO / rel
        rec = dict(entry)
        if p.exists():
            rec["sha256"] = sha256(p)
            rec["bytes"] = p.stat().st_size
            rec["git_tracked"] = is_tracked(rel)
            rec["last_commit"] = git("log", "-1", "--format=%h", "--", rel)
        else:
            rec["sha256"] = None
            rec["bytes"] = None
            rec["git_tracked"] = False
            rec["last_commit"] = None
            rec["MISSING"] = True
            missing.append(rel)
        files.append(rec)

    return {
        "_comment": ("Top-level artifact-evaluation manifest of every headline "
                     "result file the paper cites. Hashes are real SHA-256 of the "
                     "committed files. Regenerate with scripts/make_manifest.py; "
                     "verify with --check. See docs/REPRODUCE.md for the full "
                     "claim->command->file map."),
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "git_head": head,
        "git_head_short": head_short,
        "environment_that_produced_numbers": produced_env,
        "n_files": len(files),
        "n_missing": len(missing),
        "missing": missing,
        "files": files,
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(REPO / "results" / "MANIFEST.json"))
    ap.add_argument("--check", action="store_true",
                    help="recompute hashes and exit 1 if they differ from the committed manifest")
    a = ap.parse_args(argv)

    fresh = build()

    if a.check:
        out = Path(a.out)
        if not out.exists():
            print(f"[make_manifest] no manifest at {out} to check against", file=sys.stderr)
            return 1
        old = json.loads(out.read_text())
        old_h = {f["path"]: f.get("sha256") for f in old.get("files", [])}
        drift = []
        for f in fresh["files"]:
            if f["path"] in old_h and old_h[f["path"]] != f["sha256"]:
                drift.append(f["path"])
        if drift:
            print("[make_manifest] HASH DRIFT in:\n  " + "\n  ".join(drift), file=sys.stderr)
            return 1
        print(f"[make_manifest] OK — {fresh['n_files']} files match committed hashes")
        return 0

    Path(a.out).write_text(json.dumps(fresh, indent=2) + "\n")
    print(f"[make_manifest] wrote {a.out}  ({fresh['n_files']} files, "
          f"{fresh['n_missing']} missing)")
    if fresh["n_missing"]:
        print("  MISSING:\n    " + "\n    ".join(fresh["missing"]), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
