"""Generate results/MANIFEST.json — an artifact-evaluation manifest covering ALL
headline result directories (not just full_research).

Unlike results/full_research/MANIFEST.json (which the full-research run writes for
its own two output dirs), this top-level manifest is a *post-hoc* inventory of
every committed headline result file the paper cites, with:

  * a real SHA-256 hash computed from the committed file on disk (never fabricated),
  * the file size and last-commit SHA touching it (best-effort, via git),
  * the producing script (mapped explicitly, verified by grep at authoring time),
  * the runtime tier (CPU-verify vs GPU-regenerate).

It also records the environment that PRODUCED the headline numbers (from the
existing full_research/MANIFEST.json, the calibrated run env) plus the CURRENT
environment generating this manifest, and the current git HEAD.

This is a reproducibility aid, NOT a result — it is safe to regenerate any time:

    .venv/Scripts/python.exe scripts/make_manifest.py            # -> results/MANIFEST.json
    .venv/Scripts/python.exe scripts/make_manifest.py --check    # verify hashes match, exit 1 on drift

CPU-only, no torch/numpy needed (pure stdlib), seconds to run.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# The headline result files the paper cites, mapped to their producing script
# and runtime tier. Mapping was verified by grepping each filename across
# scripts/ + benchmarks/ for the write site (open(...,'w')/json.dump/savefig).
# tier: "gpu" = regenerated by a multi-day GPU run; "cpu" = re-derivable on a
# laptop FROM a (gitignored) checkpoint; "cpu-verify" = pure plotting/inventory.
# ---------------------------------------------------------------------------
HEADLINE: list[dict] = [
    # --- SOTA Transolver headline (tab:v2, abstract) ---
    {"path": "results/v2/v2_results.json",
     "script": "scripts/run_v2.py", "tier": "gpu",
     "claims": "Transolver backbone -9/-21/-25% MSE; rho_Cl 0.999; trust rho 0.625; MC-dropout coverage 0.902"},
    # --- third backbone, trust signal (tab in sec:v2) ---
    {"path": "results/mgn/mgn_results.json",
     "script": "scripts/run_mgn.py", "tier": "gpu",
     "claims": "MeshGraphNet bare trust rho 0.851"},
    # --- deep-ensemble adaptive UQ (tab:uq) ---
    {"path": "results/uq_ensemble/uq_results.json",
     "script": "scripts/run_ensemble_uq.py", "tier": "gpu",
     "claims": "deep-ensemble conformal coverage 0.915, ECE 0.074, q 2.35; ensemble-mean accuracy"},
    {"path": "results/uq_ensemble/w2_conformal_corrected.json",
     "script": "scripts/run_w2_conformal_corrected.py", "tier": "gpu",
     "claims": "W2 — conformal coverage on the deployed DEQ-corrected Transolver field"},
    # --- W1 residual-input ablation (abstract, sec:v2, limitations) ---
    {"path": "results/control/w1_capture.json",
     "script": "scripts/run_w1_capture.py", "tier": "gpu",
     "claims": "W1 — null-residual corrector matches/exceeds residual-fed (gain not from residual input)"},
    # --- force coefficients vs official AirfRANS labels (sec:v2, SOTA positioning) ---
    {"path": "results/control/force_vs_official.json",
     "script": "scripts/recompute_force_vs_official.py", "tier": "gpu",
     "claims": "vs official labels rho_D 0.839, rho_L 0.879; self-consistency 0.995/0.999 reproduced"},
    # --- per-cell vs per-case trust scope ---
    {"path": "results/control/percell_residual_error.json",
     "script": "scripts/control_percell_residual_error.py", "tier": "cpu",
     "claims": "per-cell trust 0.22 Spearman / 0.60 Pearson (case-level vs per-cell scope)"},
    # --- BC-inclusive residual robustness (residual_floor_theorem) ---
    {"path": "results/control/bc_inclusive_sweep.json",
     "script": "scripts/control_bc_inclusive_residual.py", "tier": "cpu",
     "claims": "residual-as-objective negative survives the BC (no-slip) term"},
    # --- cross-geometry cylinder OOD (sec:ood, fig:cylinder) ---
    {"path": "results/figures/cylinder_control_airfoil_ratio.json",
     "script": "scripts/control_cylinder_nearwall_artifact.py", "tier": "cpu",
     "claims": "cylinder far-field residual ~7x in-dist; near-wall ring is a generic feature (control)"},
    # --- certificates H4 / H5 / residual floor ---
    {"path": "results/certificates/h4_coverage.json",
     "script": "scripts/run_certificates.py", "tier": "cpu",
     "claims": "H4 in-distribution split-conformal coverage 0.911/0.928/0.942"},
    {"path": "results/certificates/h5_contraction.json",
     "script": "scripts/run_certificates.py", "tier": "cpu",
     "claims": "H5 DEQ contraction median 0.78 < kappa 0.9"},
    {"path": "results/certificates/residual_floor_realdata.json",
     "script": "scripts/probe_residual_floor.py", "tier": "cpu",
     "claims": "residual floor: ||r*|| mean 0.192; uniform field gives 0 (theorem H2)"},
    {"path": "results/certificates/probe_conformal_after_deq.json",
     "script": "scripts/probe_conformal_after_deq.py", "tier": "cpu",
     "claims": "conformal survives DEQ (20/20 independent split)"},
    {"path": "results/certificates/verify_conformal_corrected_field.json",
     "script": "scripts/verify_conformal_corrected_field.py", "tier": "cpu",
     "claims": "certificate on the deployed corrected field (15/15 split)"},
    # --- sensitivity sweeps (tab:iters, toggles, OOD coverage) ---
    {"path": "results/sensitivity/iters.csv",
     "script": "scripts/run_sensitivity.py", "tier": "cpu",
     "claims": "tab:iters — residual rises (0.11->0.62) while error falls (3.92->2.29)"},
    {"path": "results/sensitivity/iters.json",
     "script": "scripts/run_sensitivity.py", "tier": "cpu",
     "claims": "iteration-sensitivity sweep (json form of tab:iters)"},
    {"path": "results/sensitivity/toggles.json",
     "script": "scripts/run_sensitivity.py", "tier": "cpu",
     "claims": "trust-gate / acceptance-test toggles are structural no-ops on DEQ"},
    {"path": "results/sensitivity/ood_coverage.json",
     "script": "scripts/run_sensitivity.py", "tier": "cpu",
     "claims": "OOD conformal coverage stays in-band (empirical, sec:conformal)"},
    # --- weak-grid-backbone ablations (tab:indist, tab:ood) ---
    {"path": "results/full_research/in_dist/ablation.md",
     "script": "scripts/run_full_research.py", "tier": "gpu",
     "claims": "tab:indist — weak backbone trust 0.40->0.83; corrector trades accuracy"},
    {"path": "results/full_research/in_dist/ablation.csv",
     "script": "scripts/run_full_research.py", "tier": "gpu",
     "claims": "tab:indist (csv)"},
    {"path": "results/full_research/ood/ablation_ood.md",
     "script": "scripts/run_full_research.py", "tier": "gpu",
     "claims": "tab:ood — aoa trust collapse 0.31->0.75 rescued by corrector"},
    {"path": "results/full_research/ood/ablation_ood.csv",
     "script": "scripts/run_full_research.py", "tier": "gpu",
     "claims": "tab:ood (csv)"},
    # --- matched-budget baseline (tab:transolver) ---
    {"path": "results/baselines/table2.md",
     "script": "scripts/run_baselines.py", "tier": "gpu",
     "claims": "tab:transolver — grid backbone trails Transolver 4-60x"},
    {"path": "results/baselines/table2.csv",
     "script": "scripts/run_baselines.py", "tier": "gpu",
     "claims": "tab:transolver (csv)"},
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def git(*args: str) -> str | None:
    try:
        out = subprocess.run(["git", "-C", str(REPO), *args],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except Exception:
        return None


def is_tracked(rel: str) -> bool:
    return git("ls-files", "--error-unmatch", rel) is not None


def build() -> dict:
    head = git("rev-parse", "HEAD")
    head_short = git("rev-parse", "--short", "HEAD")

    # Environment that PRODUCED the headline numbers (calibrated run env).
    produced_env = None
    fr = REPO / "results" / "full_research" / "MANIFEST.json"
    if fr.exists():
        m = json.loads(fr.read_text())
        produced_env = {k: m.get(k) for k in
                        ("git_commit", "platform", "python", "torch",
                         "cuda_available", "cuda_toolkit", "gpu")}

    files = []
    missing = []
    for entry in HEADLINE:
        rel = entry["path"]
        p = REPO / rel
        rec = dict(entry)
        if p.exists():
            rec["sha256"] = sha256(p)
            rec["bytes"] = p.stat().st_size
            rec["git_tracked"] = is_tracked(rel)
            rec["last_commit"] = git("log", "-1", "--format=%h", "--", rel)
        else:
            rec["sha256"] = None
            rec["bytes"] = None
            rec["git_tracked"] = False
            rec["last_commit"] = None
            rec["MISSING"] = True
            missing.append(rel)
        files.append(rec)

    return {
        "_comment": ("Top-level artifact-evaluation manifest of every headline "
                     "result file the paper cites. Hashes are real SHA-256 of the "
                     "committed files. Regenerate with scripts/make_manifest.py; "
                     "verify with --check. See docs/REPRODUCE.md for the full "
                     "claim->command->file map."),
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "git_head": head,
        "git_head_short": head_short,
        "environment_that_produced_numbers": produced_env,
        "n_files": len(files),
        "n_missing": len(missing),
        "missing": missing,
        "files": files,
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(REPO / "results" / "MANIFEST.json"))
    ap.add_argument("--check", action="store_true",
                    help="recompute hashes and exit 1 if they differ from the committed manifest")
    a = ap.parse_args(argv)

    fresh = build()

    if a.check:
        out = Path(a.out)
        if not out.exists():
            print(f"[make_manifest] no manifest at {out} to check against", file=sys.stderr)
            return 1
        old = json.loads(out.read_text())
        old_h = {f["path"]: f.get("sha256") for f in old.get("files", [])}
        drift = []
        for f in fresh["files"]:
            if f["path"] in old_h and old_h[f["path"]] != f["sha256"]:
                drift.append(f["path"])
        if drift:
            print("[make_manifest] HASH DRIFT in:\n  " + "\n  ".join(drift), file=sys.stderr)
            return 1
        print(f"[make_manifest] OK — {fresh['n_files']} files match committed hashes")
        return 0

    Path(a.out).write_text(json.dumps(fresh, indent=2) + "\n")
    print(f"[make_manifest] wrote {a.out}  ({fresh['n_files']} files, "
          f"{fresh['n_missing']} missing)")
    if fresh["n_missing"]:
        print("  MISSING:\n    " + "\n    ".join(fresh["missing"]), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
