"""Generate results/MANIFEST.json — an artifact-evaluation manifest covering ALL
headline result directories (not just full_research).

Unlike results/full_research/MANIFEST.json (which the full-research run writes for
its own two output dirs), this top-level manifest is a *post-hoc* inventory of
every committed headline result file the paper cites, with:

  * a real SHA-256 hash computed from the committed file on disk (never fabricated),
  * the file size and last-commit SHA touching it (best-effort, via git),
  * the producing script (mapped explicitly, verified by grep at authoring time),
  * the runtime tier (CPU-verify vs GPU-regenerate).

It also records the environment that PRODUCED the headline numbers (from the
existing full_research/MANIFEST.json, the calibrated run env) plus the CURRENT
environment generating this manifest, and the current git HEAD.

This is a reproducibility aid, NOT a result — it is safe to regenerate any time:

    .venv/Scripts/python.exe scripts/make_manifest.py            # -> results/MANIFEST.json
    .venv/Scripts/python.exe scripts/make_manifest.py --check    # verify hashes match, exit 1 on drift

CPU-only, no torch/numpy needed (pure stdlib), seconds to run.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# The headline result files the paper cites, mapped to their producing script
# and runtime tier. Mapping was verified by grepping each filename across
# scripts/ + benchmarks/ for the write site (open(...,'w')/json.dump/savefig).
# tier: "gpu" = regenerated by a multi-day GPU run; "cpu" = re-derivable on a
# laptop FROM a (gitignored) checkpoint; "cpu-verify" = pure plotting/inventory.
# ---------------------------------------------------------------------------
HEADLINE: list[dict] = [
    # --- SOTA Transolver headline (tab:v2, abstract) ---
    {"path": "results/v2/v2_results.json",
     "script": "scripts/run_v2.py", "tier": "gpu",
     "claims": "Transolver backbone -9/-21/-25% MSE; rho_Cl 0.999; trust rho 0.625; MC-dropout coverage 0.902"},
    # --- third backbone, trust signal (tab in sec:v2) ---
    {"path": "results/mgn/mgn_results.json",
     "script": "scripts/run_mgn.py", "tier": "gpu",
     "claims": "MeshGraphNet bare trust rho 0.851"},
    # --- deep-ensemble adaptive UQ (tab:uq) ---
    {"path": "results/uq_ensemble/uq_results.json",
     "script": "scripts/run_ensemble_uq.py", "tier": "gpu",
     "claims": "deep-ensemble conformal coverage 0.915, ECE 0.074, q 2.35; ensemble-mean accuracy"},
    {"path": "results/uq_ensemble/w2_conformal_corrected.json",
     "script": "scripts/run_w2_conformal_corrected.py", "tier": "gpu",
     "claims": "W2 — conformal coverage on the deployed DEQ-corrected Transolver field"},
    # --- W1 residual-input ablation (abstract, sec:v2, limitations) ---
    {"path": "results/control/w1_capture.json",
     "script": "scripts/run_w1_capture.py", "tier": "gpu",
     "claims": "5-seed extension: backbone trust rho 0.611 +/- 0.054 (positive 5/5); corrector -8/-21/-25%; "
               "W1 null corrector matches/exceeds residual-fed on 5/5 seeds (gain not from residual input)"},
    # --- force coefficients vs official AirfRANS labels (sec:v2, SOTA positioning) ---
    {"path": "results/control/force_vs_official.json",
     "script": "scripts/recompute_force_vs_official.py", "tier": "gpu",
     "claims": "vs official labels rho_D 0.839, rho_L 0.879; self-consistency 0.995/0.999 reproduced"},
    # --- per-cell vs per-case trust scope ---
    {"path": "results/control/percell_residual_error.json",
     "script": "scripts/control_percell_residual_error.py", "tier": "cpu",
     "claims": "per-cell trust 0.22 Spearman / 0.60 Pearson (case-level vs per-cell scope)"},
    # --- BC-inclusive residual robustness (residual_floor_theorem) ---
    {"path": "results/control/bc_inclusive_sweep.json",
     "script": "scripts/control_bc_inclusive_residual.py", "tier": "cpu",
     "claims": "residual-as-objective negative survives the BC (no-slip) term"},
    # --- cross-geometry cylinder OOD (sec:ood, fig:cylinder) ---
    {"path": "results/figures/cylinder_control_airfoil_ratio.json",
     "script": "scripts/control_cylinder_nearwall_artifact.py", "tier": "cpu",
     "claims": "cylinder far-field residual ~7x in-dist; near-wall ring is a generic feature (control)"},
    # --- certificates H4 / H5 / residual floor ---
    {"path": "results/certificates/h4_coverage.json",
     "script": "scripts/run_certificates.py", "tier": "cpu",
     "claims": "H4 in-distribution split-conformal coverage 0.911/0.928/0.942"},
    {"path": "results/certificates/h5_contraction.json",
     "script": "scripts/run_certificates.py", "tier": "cpu",
     "claims": "H5 DEQ contraction median 0.78 < kappa 0.9"},
    {"path": "results/certificates/residual_floor_realdata.json",
     "script": "scripts/probe_residual_floor.py", "tier": "cpu",
     "claims": "residual floor: ||r*|| mean 0.192; uniform field gives 0 (theorem H2)"},
    {"path": "results/certificates/probe_conformal_after_deq.json",
     "script": "scripts/probe_conformal_after_deq.py", "tier": "cpu",
     "claims": "conformal survives DEQ (20/20 independent split)"},
    {"path": "results/certificates/verify_conformal_corrected_field.json",
     "script": "scripts/verify_conformal_corrected_field.py", "tier": "cpu",
     "claims": "certificate on the deployed corrected field (15/15 split)"},
    # --- sensitivity sweeps (tab:iters, toggles, OOD coverage) ---
    {"path": "results/sensitivity/iters.csv",
     "script": "scripts/run_sensitivity.py", "tier": "cpu",
     "claims": "tab:iters — residual rises (0.11->0.62) while error falls (3.92->2.29)"},
    {"path": "results/sensitivity/iters.json",
     "script": "scripts/run_sensitivity.py", "tier": "cpu",
     "claims": "iteration-sensitivity sweep (json form of tab:iters)"},
    {"path": "results/sensitivity/toggles.json",
     "script": "scripts/run_sensitivity.py", "tier": "cpu",
     "claims": "trust-gate / acceptance-test toggles are structural no-ops on DEQ"},
    {"path": "results/sensitivity/ood_coverage.json",
     "script": "scripts/run_sensitivity.py", "tier": "cpu",
     "claims": "OOD conformal coverage stays in-band (empirical, sec:conformal)"},
    # --- weak-grid-backbone ablations (tab:indist, tab:ood) ---
    {"path": "results/full_research/in_dist/ablation.md",
     "script": "scripts/run_full_research.py", "tier": "gpu",
     "claims": "tab:indist — weak backbone trust 0.40->0.83; corrector trades accuracy"},
    {"path": "results/full_research/in_dist/ablation.csv",
     "script": "scripts/run_full_research.py", "tier": "gpu",
     "claims": "tab:indist (csv)"},
    {"path": "results/full_research/ood/ablation_ood.md",
     "script": "scripts/run_full_research.py", "tier": "gpu",
     "claims": "tab:ood — aoa trust collapse 0.31->0.75 rescued by corrector"},
    {"path": "results/full_research/ood/ablation_ood.csv",
     "script": "scripts/run_full_research.py", "tier": "gpu",
     "claims": "tab:ood (csv)"},
    # --- matched-budget baseline (tab:transolver) ---
    {"path": "results/baselines/table2.md",
     "script": "scripts/run_baselines.py", "tier": "gpu",
     "claims": "tab:transolver — grid backbone trails Transolver 4-60x"},
    {"path": "results/baselines/table2.csv",
     "script": "scripts/run_baselines.py", "tier": "gpu",
     "claims": "tab:transolver (csv)"},
    # --- second dataset (DeepCFD, laminar bluff bodies) ---
    {"path": "results/deepcfd/deepcfd_results.json",
     "script": "scripts/run_deepcfd.py", "tier": "gpu",
     "claims": "DeepCFD OOD trust rho 0.770 +/- 0.119 (3 seeds, interior residual)"},
    {"path": "results/deepcfd/deepcfd_trust_percase.json",
     "script": "scripts/make_fig_deepcfd_trust.py", "tier": "cpu",
     "claims": "per-case (residual, rel-L2) dump behind fig:deepcfd + bootstrap CIs"},
    # --- selective prediction / risk-coverage (fig:risk_coverage) ---
    {"path": "results/selective/selective_prediction.json",
     "script": "scripts/run_selective_prediction.py", "tier": "cpu",
     "claims": "AUROC 0.87-0.91 residual, 0.905 fused; ~91% of oracle error reduction at 10% rejection"},
    {"path": "results/selective/selective_percase.json",
     "script": "scripts/run_selective_prediction.py", "tier": "cpu",
     "claims": "per-case scores/errors for all arms (bootstrap-CI input)"},
    {"path": "results/figures/fig_risk_coverage.pdf",
     "script": "scripts/run_selective_prediction.py", "tier": "cpu",
     "claims": "fig:risk_coverage (risk-coverage curves + AUROC bars)"},
    # --- multi-split conformal robustness (sec:conformal) ---
    {"path": "results/uq_ensemble/multisplit_conformal.json",
     "script": "scripts/run_multisplit_conformal.py", "tier": "cpu",
     "claims": "20-split conformal: coverage 0.895-0.902 all arms; corrected-p q 2.26->2.02-2.07"},
    # --- bootstrap CIs on the trust-signal Spearman headlines ---
    {"path": "results/control/bootstrap_spearman_ci.json",
     "script": "scripts/bootstrap_spearman_ci.py", "tier": "cpu",
     "claims": "case-level bootstrap 95% CIs; all arms exclude zero (ensemble 0.610 [0.51,0.70])"},
    # --- force-integrator repair (sec:v2 force paragraphs) ---
    {"path": "results/control/integrator_design.json",
     "script": "scripts/design_force_integrator.py", "tier": "cpu",
     "claims": "GT-field integrator variants: CV rho_L 1.00 / cd med 0.23; wall cl med 0.046"},
    {"path": "results/control/force_vs_official_multischeme.json",
     "script": "scripts/recompute_force_multischeme.py", "tier": "gpu",
     "claims": "pred fields: CV lift rho_L 0.998 +/- 0.001, cl med err 3.6-3.9%/seed; drag model-limited"},
    # --- spatial trust localization (per-cell vs patch scope) ---
    {"path": "results/control/percell_localization.json",
     "script": "scripts/percell_trust_localization.py", "tier": "cpu",
     "claims": "cell-level rho 0.166 -> 16x16-patch 0.323 (93% of cases improve); patch AUROC 0.68-0.72"},
    # --- acceptance-gate measurement (sec:iters, the residual-as-GATE verdict) ---
    {"path": "results/control/acceptance_gate.json",
     "script": "scripts/measure_acceptance_gate.py", "tier": "gpu",
     "claims": "monotone-residual gate admits a step on 99.8%% of deployed cases (the full "
               "correction on 50.7%%); the admitted step lowers true rel-L2 error on 89.3%% of "
               "them by a median 5.8%% -- the guarantee is real AND useful, not vacuous"},
    # --- audit wall-clock cost (selective-prediction paragraph) ---
    {"path": "results/control/audit_cost.json",
     "script": "scripts/measure_audit_cost.py", "tier": "cpu",
     "claims": "full audit median 1.7 ms/case (1 CPU thread) vs ~25-min 16-core RANS solve (~1e-6)"},
    # --- is the nu_t channel actually learned? (Limitations, sec:method) ---
    {"path": "results/control/nut_learned.json",
     "script": "scripts/check_nut_learned.py", "tier": "cpu",
     "claims": "nu_t over fluid cells mean 8.19e-5 vs laminar nu 1.56e-5 (5.2x, 84%% of nu_eff); channel is learned, backbone-dependently: R2 0.996 grid backbone, 0.67-0.70 MeshGraphNet against nu_t's own fluid-masked variance"},
    # --- does any no-slip weight rescue the residual? (sec:residual_floor) ---
    {"path": "results/control/bc_weight_sweep.json",
     "script": "scripts/bc_weight_sweep.py", "tier": "cpu",
     "claims": "post-hoc sweep of the no-slip weight lambda on already-logged components: the uniform field stays a spurious minimum and the residual still rises as error falls, for every lambda >= 0 (closed form, no crossover weight)"},
    # --- full-pipeline wall-clock cost (sec:cost, JCP complexity requirement) ---
    {"path": "results/control/inference_cost.json",
     "script": "scripts/measure_inference_cost.py", "tier": "gpu",
     "claims": "deployed solve 3822 ms/case (backbone 2080 + correction 1747) on one RTX 4070 Ti; audit 1.13 ms = 0.03%% of it; 5-member ensemble 4.86x a single backbone "
               "(linear in M, measured not assumed); audit O(N) in cells, slope 0.64 over a 16x range; ~286x faster end-to-end than the ~25-min 16-core RANS solve"},
    # --- ensemble-size study (limitations: choice of M measured) ---
    {"path": "results/uq_ensemble/mstudy.json",
     "script": "scripts/run_ensemble_mstudy.py", "tier": "gpu",
     "claims": "M=2..5 all 26 subsets: fused AUROC 0.905-0.912 + coverage on-target at every M; "
               "band adaptivity needs M (q_p 2.35->9.98, ECE 0.074->0.199 as M 5->2)"},
    # --- graphical abstract (JCP submission artefact) ---
    {"path": "results/figures/graphical_abstract.pdf",
     "script": "scripts/make_graphical_abstract.py", "tier": "cpu",
     "claims": "predict -> audit -> calibrate -> decide strip; median-error showcase case, committed numbers only"},
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def git(*args: str) -> str | None:
    try:
        out = subprocess.run(["git", "-C", str(REPO), *args],
                             capture_output=True, text=True, check=True)
        return out.stdout.strip()
    except Exception:
        return None


def is_tracked(rel: str) -> bool:
    return git("ls-files", "--error-unmatch", rel) is not None


def build() -> dict:
    head = git("rev-parse", "HEAD")
    head_short = git("rev-parse", "--short", "HEAD")

    # Environment that PRODUCED the headline numbers (calibrated run env).
    produced_env = None
    fr = REPO / "results" / "full_research" / "MANIFEST.json"
    if fr.exists():
        m = json.loads(fr.read_text())
        produced_env = {k: m.get(k) for k in
                        ("git_commit", "platform", "python", "torch",
                         "cuda_available", "cuda_toolkit", "gpu")}

    files = []
    missing = []
    for entry in HEADLINE:
        rel = entry["path"]
        p = REPO / rel
        rec = dict(entry)
        if p.exists():
            rec["sha256"] = sha256(p)
            rec["bytes"] = p.stat().st_size
            rec["git_tracked"] = is_tracked(rel)
            rec["last_commit"] = git("log", "-1", "--format=%h", "--", rel)
        else:
            rec["sha256"] = None
            rec["bytes"] = None
            rec["git_tracked"] = False
            rec["last_commit"] = None
            rec["MISSING"] = True
            missing.append(rel)
        files.append(rec)

    return {
        "_comment": ("Top-level artifact-evaluation manifest of every headline "
                     "result file the paper cites. Hashes are real SHA-256 of the "
                     "committed files. Regenerate with scripts/make_manifest.py; "
                     "verify with --check. See docs/REPRODUCE.md for the full "
                     "claim->command->file map."),
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "git_head": head,
        "git_head_short": head_short,
        "environment_that_produced_numbers": produced_env,
        "n_files": len(files),
        "n_missing": len(missing),
        "missing": missing,
        "files": files,
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(REPO / "results" / "MANIFEST.json"))
    ap.add_argument("--check", action="store_true",
                    help="recompute hashes and exit 1 if they differ from the committed manifest")
    a = ap.parse_args(argv)

    fresh = build()

    if a.check:
        out = Path(a.out)
        if not out.exists():
            print(f"[make_manifest] no manifest at {out} to check against", file=sys.stderr)
            return 1
        old = json.loads(out.read_text())
        old_h = {f["path"]: f.get("sha256") for f in old.get("files", [])}
        drift = []
        for f in fresh["files"]:
            if f["path"] in old_h and old_h[f["path"]] != f["sha256"]:
                drift.append(f["path"])
        if drift:
            print("[make_manifest] HASH DRIFT in:\n  " + "\n  ".join(drift), file=sys.stderr)
            return 1
        print(f"[make_manifest] OK — {fresh['n_files']} files match committed hashes")
        return 0

    Path(a.out).write_text(json.dumps(fresh, indent=2) + "\n")
    print(f"[make_manifest] wrote {a.out}  ({fresh['n_files']} files, "
          f"{fresh['n_missing']} missing)")
    if fresh["n_missing"]:
        print("  MISSING:\n    " + "\n    ".join(fresh["missing"]), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
